### ISSUE TITLE
Bug in logging / exception handling

### ISSUE THREAD

**Issue by kad-jagtt** [PDOK/geopackage-validator#26]
A broken gpkg results in an incomplete validation report. 

--------

I got the following output when validating a geo package:
```json
{
    "geopackage_validator_version": "0.4.dev0",
    "start_time": "2020-11-06T10:06:19.447985",
    "duration_seconds": 0,
    "geopackage": "",
    "success": false,
    "validations_executed": [],
    "results": [
        {
            "validation_code": "UNKNOWN",
            "validation_description": "No unexpected errors must occur.",
            "level": "error",
            "locations": [
                "list indices must be integers or slices, not str"
            ]
        }
    ]
}
```

Below the full traceback for the record:
```bash
Traceback (most recent call last):
  File "/home/ubuntu/.local/share/virtualenvs/geopackage-validator-zn3H4vhN/bin/geopackage-validator", line 33, in <module>
    sys.exit(load_entry_point('geopackage-validator', 'console_scripts', 'geopackage-validator')())
  File "/home/ubuntu/.local/share/virtualenvs/geopackage-validator-zn3H4vhN/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/share/virtualenvs/geopackage-validator-zn3H4vhN/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/share/virtualenvs/geopackage-validator-zn3H4vhN/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.local/share/virtualenvs/geopackage-validator-zn3H4vhN/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/share/virtualenvs/geopackage-validator-zn3H4vhN/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/geopackage-validator/geopackage_validator/cli.py", line 139, in geopackage_validator_command
    validate(
  File "/home/ubuntu/geopackage-validator/geopackage_validator/validate.py", line 89, in validate
    log_output(
  File "/home/ubuntu/geopackage-validator/geopackage_validator/output.py", line 25, in log_output
    "success": is_success(results),
  File "/home/ubuntu/geopackage-validator/geopackage_validator/output.py", line 36, in is_success
    validation_code = result["validation_code"]
TypeError: list indices must be integers or slices, not str
```

The error is triggered here:
https://github.com/PDOK/geopackage-validator/blob/c0498af76cf8286bba0022853e8fa10f94a64afd/geopackage_validator/output.py#L35-L36

A list of dictonaries is expected in the result_list but one of the results is a list.
The list contains an error from GDAL:
`This version of GeoPackage user_version=0x0000283C (10300, v1.3.0) on '/path/to/file.gpkg' may only be partially supported`

**More detail**
https://github.com/PDOK/geopackage-validator/blob/c0498af76cf8286bba0022853e8fa10f94a64afd/geopackage_validator/validations/validate_all.py#L147-L156

```bash
ipdb> r = list(geometry_type_names)
--Return--
[{'level': 'error', 'locations': ["<class 'TypeError'>"], 'validation_code': 'UNKNOWN', 'validation_description': 'No unexpecte...s must occur.'}]
```
The code tries to extend the result_list with a new item but got a TypeError.

This occurs in the gpkg_geometry_valid function with validation code RQ14

**Comment by RoelvandenBerg** [comment]
Gefixt in 0.4.1
